demo_mode: true

binary_server:
  webdav_url: "http://binary-server:8080"
  ssh_host: "binary-server"
  ssh_port: 22
  ssh_username: "binmanager"
  ssh_key_path: "/home/app/.ssh/id_rsa"
  binary_root_path: "/data/binaries"

disk:
  trigger_threshold_percent: 90
  target_threshold_percent: 80
  check_interval_minutes: 5

retention_types:
  - name: "nightly"
    retention_days: 7
    priority: 1
  - name: "release"
    retention_days: 90
    priority: 3
  - name: "temp"
    retention_days: 1
    priority: 0

project_mappings:
  - pattern: "ProjectA"
    type: "nightly"
  - pattern: "ProjectB"
    type: "release"
  - pattern: "Temp"
    type: "temp"

auth:
  shared_password: "changeme"
  jwt_secret: "change-this-to-a-random-secret-in-production"
